### ISSUE TITLE
How to used D2RM in Azure DevOps

### ISSUE THREAD

**Issue by ziselsberger** [ziselsberger/use_doc_to_readme#6]
```yaml
pool: 
  vmImage: ubuntu-latest

jobs:
- job:
  displayName: Doc2Readme
  steps:
  - checkout: self
    persistCredentials: true 
    clean: true 
    fetchDepth: 0
  - script: |
      git config --global user.email "$(Build.RequestedForEmail)"
      git config --global user.name "$(Build.RequestedFor)"
    displayName: Set git config
  - script: |
      git pull --rebase origin $(Build.SourceBranch)
      git clone 'https://github.com/ziselsberger/doc_to_readme.git'
      cp ./doc_to_readme/src/doc_to_md/doc_to_md.py .
      rm -rf doc_to_readme
      python doc_to_md.py -f README.md -e doc_to_md --separated
      rm doc_to_md.py
      lines=$(git status -s | wc -l)
      if [ $lines -gt 0 ];then
        git add "README.md"
        git commit -m "Auto-update README.md [skip ci]"
        git push origin HEAD:$(Build.SourceBranch)
      fi
    displayName: Add module documentation to README
```
